### ISSUE TITLE
Sync client and server time

### ISSUE THREAD

**Issue by cthill** [cthill/realtime-tournament#47]
Use an NTP-like protocol to sync client time with server time.

https://gist.github.com/mfbx9da4/27613da25ac7ba5c4118
https://en.wikipedia.org/wiki/Network_Time_Protocol

**Comment by bmzhao** [comment]
https://github.com/bmzhao/computer-graphics-hw/blob/project/src/project/MultiplayerState.java#L72

https://github.com/bmzhao/graphics-project-server/commit/3bbc758eee943b4faba426a04dda6f380626a40b#diff-7ca3bd00d7f2ed4cc27ca8a44208d543R47

**Comment by cthill** [comment]
Done: abfda1fa86d8e0d4923979746f1ec9971df3b447
It's pretty jank (doesn't account for network latency) but it's good enough for now. We really only need to be accurate to within a couple of seconds. In the future, we should modify js/app/svc/time.js to do something like NTP over the websocket.
